name: "Super-Linter"

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "*" ]

jobs:
  clang-format-check:
    runs-on: [ "ubuntu-latest" ]
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v4"
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: "Validation with Super-Linter"
        uses: "super-linter/super-linter@v6.3.0"
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CLANG_FORMAT: true
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
